import Head from 'next/head'
import styles from '../styles/Home.module.css'
import '@carbon/ibm-products/css/index.min.css'
import { SidePanel } from '@carbon/ibm-products/lib/components/SidePanel'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <SidePanel title="@carbon/ibm-products/lib/components/SidePanel" open>
          <h1>Hello World</h1>
        </SidePanel>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>
    </div>
  )
}
